# Inherit base settings from https://github.com/jenkinsci/.github/blob/master/.github/release-drafter.yml
_extends: .github
name-template: OES Template v$RESOLVED_VERSION
tag-template: oes-template-$RESOLVED_VERSION
version-template: $MAJOR.$MINOR.$PATCH

# Basic SemVer version resolver
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch